export const DISPLAY_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = "HIDE_ALERT"
export const REGISTER_ALERT = "REGISTER_ALERT"

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"

export const POST_ERROR = "POST_ERROR"
export const POST_SUCCESS = "POST_SUCCESS"

export const POST_DELETE_ERROR = "POST_DELETE_ERROR"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"

export const USER_ADD = "USER_ADD"
export const USER_DEL = "USER_DEL"

export const LOGOUT_USER = "LOGOUT_USER"